### ISSUE TITLE
QPDF Error while building wheel on Ubuntu 20.04

### ISSUE THREAD

**Issue by VincentSchmid** [pikepdf/pikepdf#292]
When installing pikepdf on my rpi4 using Ubuntu 20.04 python 3.9.6
I get errors.

I think it's something to do with qpdf, but I'm pretty sure I have it installed, I have the following package:
`libqpdf-dev`

```
ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/bin/python3.9 /home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpwgvjqcyq
       cwd: /tmp/pip-install-buckp2i4/pikepdf_5fd3b0f4a8b54940b37c5047dd22bc0b
  Complete output (101 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.9
  creating build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/__init__.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/objects.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/jbig2.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/_version.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/codec.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/_methods.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/_cpphelpers.py -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/_xml.py -> build/lib.linux-aarch64-3.9/pikepdf
  creating build/lib.linux-aarch64-3.9/pikepdf/models
  copying src/pikepdf/models/metadata.py -> build/lib.linux-aarch64-3.9/pikepdf/models
  copying src/pikepdf/models/__init__.py -> build/lib.linux-aarch64-3.9/pikepdf/models
  copying src/pikepdf/models/matrix.py -> build/lib.linux-aarch64-3.9/pikepdf/models
  copying src/pikepdf/models/outlines.py -> build/lib.linux-aarch64-3.9/pikepdf/models
  copying src/pikepdf/models/image.py -> build/lib.linux-aarch64-3.9/pikepdf/models
  copying src/pikepdf/models/encryption.py -> build/lib.linux-aarch64-3.9/pikepdf/models
  running egg_info
  listing git files failed - pretending there aren't any
  writing manifest file 'src/pikepdf.egg-info/SOURCES.txt'
  copying src/pikepdf/_qpdf.pyi -> build/lib.linux-aarch64-3.9/pikepdf
  copying src/pikepdf/py.typed -> build/lib.linux-aarch64-3.9/pikepdf
  running build_ext
  creating build/temp.linux-aarch64-3.9
  creating build/temp.linux-aarch64-3.9/src
  creating build/temp.linux-aarch64-3.9/src/qpdf
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-p4na7eje/overlay/lib/python3.9/site-packages/pybind11/include -I/home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/include -I/home/ubuntu/.pyenv/versions/3.9.6/include/python3.9 -c src/qpdf/annotation.cpp -o build/temp.linux-aarch64-3.9/src/qpdf/annotation.o -fvisibility=hidden -g0 -std=c++17
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-p4na7eje/overlay/lib/python3.9/site-packages/pybind11/include -I/home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/include -I/home/ubuntu/.pyenv/versions/3.9.6/include/python3.9 -c src/qpdf/embeddedfiles.cpp -o build/temp.linux-aarch64-3.9/src/qpdf/embeddedfiles.o -fvisibility=hidden -g0 -std=c++17
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-p4na7eje/overlay/lib/python3.9/site-packages/pybind11/include -I/home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/include -I/home/ubuntu/.pyenv/versions/3.9.6/include/python3.9 -c src/qpdf/object.cpp -o build/temp.linux-aarch64-3.9/src/qpdf/object.o -fvisibility=hidden -g0 -std=c++17
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-p4na7eje/overlay/lib/python3.9/site-packages/pybind11/include -I/home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/include -I/home/ubuntu/.pyenv/versions/3.9.6/include/python3.9 -c src/qpdf/nametree.cpp -o build/temp.linux-aarch64-3.9/src/qpdf/nametree.o -fvisibility=hidden -g0 -std=c++17
  src/qpdf/embeddedfiles.cpp:14:10: fatal error: qpdf/QPDFFileSpecObjectHelper.hh: No such file or directory
     14 | #include <qpdf/QPDFFileSpecObjectHelper.hh>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-p4na7eje/overlay/lib/python3.9/site-packages/pybind11/include -I/home/ubuntu/.pyenv/versions/3.9.6/envs/scnr/include -I/home/ubuntu/.pyenv/versions/3.9.6/include/python3.9 -c src/qpdf/object_convert.cpp -o build/temp.linux-aarch64-3.9/src/qpdf/object_convert.o -fvisibility=hidden -g0 -std=c++17
  error: command '/usr/bin/gcc' failed with exit code 1
  src/qpdf/nametree.cpp:54:31: error: ‘iterator’ in ‘class QPDFNameTreeObjectHelper’ does not name a type
     54 |     QPDFNameTreeObjectHelper::iterator begin() { return this->ntoh.begin(); }
        |                               ^~~~~~~~
  src/qpdf/nametree.cpp:55:31: error: ‘iterator’ in ‘class QPDFNameTreeObjectHelper’ does not name a type
     55 |     QPDFNameTreeObjectHelper::iterator end() { return this->ntoh.end(); }
        |                               ^~~~~~~~
  src/qpdf/nametree.cpp: In constructor ‘NameTreeHolder::NameTreeHolder(QPDFObjectHandle, bool)’:
  src/qpdf/nametree.cpp:24:52: error: no matching function for call to ‘QPDFNameTreeObjectHelper::QPDFNameTreeObjectHelper(QPDFObjectHandle&, QPDF&, bool&)’
     24 |         : ntoh(oh, *oh.getOwningQPDF(), auto_repair)
        |                                                    ^
  In file included from src/qpdf/nametree.cpp:14:
  /usr/include/qpdf/QPDFNameTreeObjectHelper.hh:44:5: note: candidate: ‘QPDFNameTreeObjectHelper::QPDFNameTreeObjectHelper(QPDFObjectHandle)’
     44 |     QPDFNameTreeObjectHelper(QPDFObjectHandle);
        |     ^~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/qpdf/QPDFNameTreeObjectHelper.hh:44:5: note:   candidate expects 1 argument, 3 provided
  /usr/include/qpdf/QPDFNameTreeObjectHelper.hh:40:7: note: candidate: ‘QPDFNameTreeObjectHelper::QPDFNameTreeObjectHelper(const QPDFNameTreeObjectHelper&)’
     40 | class QPDFNameTreeObjectHelper: public QPDFObjectHelper
        |       ^~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/qpdf/QPDFNameTreeObjectHelper.hh:40:7: note:   candidate expects 1 argument, 3 provided
  src/qpdf/nametree.cpp: In member function ‘void NameTreeHolder::insert(const string&, QPDFObjectHandle)’:
  src/qpdf/nametree.cpp:44:26: error: ‘class QPDFNameTreeObjectHelper’ has no member named ‘insert’
     44 |         (void)this->ntoh.insert(key, value);
        |                          ^~~~~~
  src/qpdf/nametree.cpp: In member function ‘void NameTreeHolder::remove(const string&)’:
  src/qpdf/nametree.cpp:49:34: error: ‘class QPDFNameTreeObjectHelper’ has no member named ‘remove’
     49 |         bool result = this->ntoh.remove(key);
        |                                  ^~~~~~
  src/qpdf/nametree.cpp: At global scope:
  src/qpdf/nametree.cpp:78:31: error: ‘iterator’ in ‘class QPDFNameTreeObjectHelper’ does not name a type
     78 |     QPDFNameTreeObjectHelper::iterator iter;
        |                               ^~~~~~~~
  src/qpdf/nametree.cpp: In constructor ‘NameTreeIterator::NameTreeIterator(std::shared_ptr<NameTreeHolder>)’:
  src/qpdf/nametree.cpp:63:68: error: class ‘NameTreeIterator’ does not have any field named ‘iter’
     63 |     NameTreeIterator(std::shared_ptr<NameTreeHolder> nt) : nt(nt), iter(nt->begin()) {}
        |                                                                    ^~~~
  src/qpdf/nametree.cpp:63:77: error: ‘using element_type = class NameTreeHolder’ {aka ‘class NameTreeHolder’} has no member named ‘begin’
     63 |     NameTreeIterator(std::shared_ptr<NameTreeHolder> nt) : nt(nt), iter(nt->begin()) {}
        |                                                                             ^~~~~
  src/qpdf/nametree.cpp: In member function ‘std::pair<std::__cxx11::basic_string<char>, QPDFObjectHandle> NameTreeIterator::next()’:
  src/qpdf/nametree.cpp:67:19: error: ‘class NameTreeIterator’ has no member named ‘iter’
     67 |         if (this->iter == this->nt->end())
        |                   ^~~~
  src/qpdf/nametree.cpp:67:37: error: ‘using element_type = class NameTreeHolder’ {aka ‘class NameTreeHolder’} has no member named ‘end’
     67 |         if (this->iter == this->nt->end())
        |                                     ^~~
  src/qpdf/nametree.cpp:69:20: error: ‘class NameTreeIterator’ has no member named ‘iter’
     69 |         if (!this->iter.valid())
        |                    ^~~~
  src/qpdf/nametree.cpp:71:31: error: ‘class NameTreeIterator’ has no member named ‘iter’
     71 |         auto result = *(this->iter);
        |                               ^~~~
  src/qpdf/nametree.cpp:72:15: error: ‘class NameTreeIterator’ has no member named ‘iter’
     72 |         this->iter++;
        |               ^~~~
  src/qpdf/object.cpp: In function ‘PointerHolder<Buffer> get_stream_data(QPDFObjectHandle&, qpdf_stream_decode_level_e)’:
  src/qpdf/object.cpp:280:52: error: ‘class QPDFObjGen’ has no member named ‘unparse’
    280 |             std::string("object ") + h.getObjGen().unparse(),
        |                                                    ^~~~~~~
  src/qpdf/object.cpp:273:29: warning: control reaches end of non-void function [-Wreturn-type]
    273 |     } catch (const QPDFExc &e) {
        |                             ^
  ----------------------------------------
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf, which is required to install pyproject.toml-based projects
```

**Comment by jbarlow83** [comment]
The version of qpdf provided with Ubuntu 20.04 is too old to compile pikepdf. It might work with 21.10. Or use the procedure in the install documentation to build from a custom build of qpdf.
