### ISSUE TITLE
Is it possible to compile on ppc64 (AIX 6.1)?

### ISSUE THREAD

**Issue by mgtremaine** [pikepdf/pikepdf#268]
First I apologies for the odd niche question. I was tasked with building ocrmypdf on a IBM (Power6) running AIX 6.1 . So I need sanity check to see if I'm tilting at the wrong windmill. If you have any insight (including never going work) I'd appreciate it.

I manage to get all the way up pikepdf where I final hit a wall I can not seem to solve. In the linking stage with ld_so_aix it just will not import the QPDF symbols. The attached file has the command line output first 60 lines of the -bnoquiet info

The libqpfd.a file is 
-bash-5.1$ ls -al /opt/freeware/lib/libqpdf.a
-rwxr-xr-x    1 root     system     55914473 Nov 09 09:10 /opt/freeware/lib/libqpdf.a

Sample Undefined errors...

ld: 0711-224 WARNING: Duplicate symbol: __dso_handle
ld: 0711-317 ERROR: Undefined symbol: typeinfo for QPDFSystemError
ld: 0711-317 ERROR: Undefined symbol: .QPDFObjectHandle::QPDFObjectHandle()
ld: 0711-317 ERROR: Undefined symbol: .QPDFObjectHandle::getName[abi:cxx11]() 

[pikepdf_aix_details.txt](https://github.com/pikepdf/pikepdf/files/7508323/pikepdf_aix_details.txt)

**Comment by jbarlow83** [comment]
About 15 years ago a co-worker of mine was tasked with porting the company's software (Java + Oracle backend) to an old AIX 5.1 box. He managed it after a few weeks and a hell of a lot of swearing.

You should probably be aware that Tesseract OCR, which you'll need for ocrmypdf, relies pretty heavily on SIMD and does not have POWER SIMD implementation, so if it compiles at all it will be quite slow. So there's another hurdle down the road.
https://github.com/tesseract-ocr/tesseract/blob/main/src/arch/simddetect.cpp

Anyway, it looks like the issue may be in the vague direction of qpdf and pikepdf being compiled with a different ABI or C++ standard. It could also have something to do with how symbol visibility is handled, i.e. can you use the equivalent of `nm` and check that `libqpdf.a` is exporting the expected symbols? 

pikepdf's build system via setuptools (such as it is) expects qpdf to be a shared object. I'm not sure how well it handles static libraries.

(If it helps, Debian Linux has ppc64 ports of ocrmypdf, pikepdf and tesseract - maybe a VM would be easier.)

**Comment by mgtremaine** [comment]
Thanks for the braincells. I looked through nm results and they do look odd so I suspect the breakdown is there, the static libraries and just not getting used they way need, and sorting it out is probably a giant waste of time.

 Your point about the POWER SIMD is good also, I was worried about performance just because this box is older and honestly wrong tool for the job. Tesseract did compile and I ran a few small test images through it and it was fine, but really this probably not how they need use this. I'll push back on it (then uninstall they Kitchen-Sink that I had to build up). 

Thanks again,
-Mike
