### ISSUE TITLE
pikepdf cannot be installed on Termux

### ISSUE THREAD

**Issue by valpogus** [pikepdf/pikepdf#189]
I have been trying to install pikepdf on [Termux](https://termux.com/). I started with the naive way:

```shell
python3 -m pip install --user pikepdf
```

which breaks with the following errors:

> [...]
> ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)
> [...]
> ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
> [...]

This is to be expected, because Android does not support sem_open() (see https://github.com/termux/termux-packages/issues/570 for a detailed explanation).

Since I remembered that long ago I had pikepdf installed as a dependency of other project, I looked for the newest version that works on Termux, which is 2.1.2, right before parallel compile was enabled (again) on 2.2.0.

So I edited the `setup.py` file to disable parallel compile on Termux (https://github.com/valpogus/pikepdf/commit/07d324b795fbfbc4b4918cd77f5e0b970397fef4) and tried to build from my branch:

```shell
apt-get --yes update
apt-get --yes install build-essential git libjpeg-turbo qpdf zlib
rm -rf ~/.cache/pip
python3 -m pip install --user 'git+https://github.com/valpogus/pikepdf.git@disable_parallel_compile_termux'
```

which works.

The logic to detect Termux was taken from [here](https://github.com/termux/termux-packages/blob/16b0fabfcdb5dbf857ebfef64980e1dacb2e08ca/build-package.sh#L9) and translated to Python. Sadly I have found no method on the standard libraries sys, os or platform that return "Android" as operating system.

Would you consider adding such a patch or is it too specific? Should I open a pull request?

**Comment by jbarlow83** [comment]
Yes, I'd be happy to add a patch for pikepdf for this because it's more important for compiling to work than for it to be parallel.

I also recommend you submit to patch pybind11 against `pybind11/setup_helpers.py`, to patch the `ParallelCompile` class itself to error out if standard multiprocessing is not available. Rather than detecting termux, there should be a test failing to import from multiprocessing. Some other platforms e.g. AWS Lambda also lack standard multiprocessing. That would fix all projects that depend on pybind11.

**Comment by valpogus** [comment]
This is the Pull Request for pikepdf: https://github.com/pikepdf/pikepdf/pull/190
I'll take a look at pybind11 and see if I can also create a more generic patch there.

**Comment by valpogus** [comment]
@jbarlow83 
Reading the code from pybind11 I have learned that an environment variable can be used to control the number of build jobs in pybind11. You can take a look at the commit https://github.com/valpogus/pikepdf/commit/8e5b0e1bdea17e0ad584182667e85696b1cd659d and see if that is a more generic solution for building pikepdf on platforms without multiprocessing.
I have named the variable PYBIND11_NUM_BUILD_JOBS simply as an example.
