### ISSUE TITLE
pikepdf 10.x outline API is totally broken and undocumented — unusable compared to PyMuPDF

### ISSUE THREAD

**Issue by bigeast** [pikepdf/pikepdf#683]
## Summary

I've spent hours trying to add a simple hierarchical outline (table of contents) to a PDF using pikepdf 10.0.2, and it turned into a nightmare.  
Many methods mentioned in examples or previous versions simply don't exist anymore, and the documentation does not match the actual API.  

This library used to be a clean wrapper around qpdf, but now it feels inconsistent and unmaintained.  
Even basic operations like writing an outline (bookmarks) are impossible without trial-and-error across multiple versions.

---

## Environment

- pikepdf version: **10.0.2**
- Python version: *3.14.0*
- OS: macOS 15.7.1

---

## What I Tried

Here are a few examples of the chaos:

```python
import pikepdf
from pikepdf.models import OutlineItem

pdf = pikepdf.open("input.pdf")
outline = pdf.open_outline()

# none of these worked in 10.0.2
outline.clear()            # AttributeError: 'Outline' object has no attribute 'clear'
outline.remove_all()       # AttributeError: no such method
pdf.save_outline()         # AttributeError: did you mean 'open_outline'?
outline.write()            # AttributeError: 'Outline' object has no attribute 'write'
outline.to_list()          # AttributeError: 'Outline' object has no attribute 'to_list'
```

There is no clear migration guide between pikepdf 9 → 10 → 11.
The same code examples found on StackOverflow or even in your own documentation completely fail to run.

---

## Expected Behavior

Something like this should just work (and used to in earlier versions):

```python
pdf = pikepdf.open("input.pdf")
outline = pdf.open_outline()
outline.clear()
outline.append(OutlineItem("Chapter 1", pdf.pages[0]))
pdf.save("output.pdf")
```

---

## Actual Behavior

None of the documented or intuitive methods work.
There is no consistent way to:

Clear an existing outline
Append new OutlineItems
Write it back to the file

It’s impossible to even know what type pdf.open_outline() returns, since it behaves differently in every release.

---

## Why this matters

pikepdf is supposed to be a high-level Python interface to qpdf, but currently:

* API changes break backward compatibility with every release
* Documentation lags behind implementation
* No stable examples or migration notes exist

This makes pikepdf effectively unusable for production, especially for something as common as adding a Table of Contents.

---

## Suggestion

Please:

* Provide a clear, versioned migration guide for 8.x → 9.x → 10.x → 11.x.
* Add real examples for creating hierarchical outlines.
* Stop silently changing core APIs without documentation updates.
* Consider freezing the API or adopting semantic versioning properly.

If you want to see how a sane PDF API works, look at PyMuPDF (fitz):

```python
import fitz
doc = fitz.open("input.pdf")
doc.set_toc([[1, "Section 1", 1], [2, "Chapter 1", 3]])
doc.save("output.pdf")
```

## tl;dr

> pikepdf’s outline API is broken, undocumented, and unstable.
> Please fix it or officially deprecate it — right now, it's wasting developers’ time.

**Comment by qooxzuub** [comment]
This issue comes across as a rant, which isn't ideal. I found this documentation easy enough to follow:

https://pikepdf.readthedocs.io/en/latest/topics/outlines.html

No idea if the API has been unstable across different releases, but I'd be surprised if it has changed radically in the manner you suggest.

**Comment by jbarlow83** [comment]
The API has been fairly stable.
