### ISSUE TITLE
Fails to build with qpdf 8.4.2

### ISSUE THREAD

**Issue by QuLogic** [pikepdf/pikepdf#109]
I didn't see any note in the 1.17.0 release notes about increased requirements, but it fails to [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=47095932) against qpdf 8.4.2:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -DVERSION_INFO="1.17.0" -I/usr/include/pybind11 -I/usr/include/python3.7m -c src/qpdf/qpdf_pagelist.cpp -o build/temp.linux-x86_64-3.7/src/qpdf/qpdf_pagelist.o -std=c++14 -fvisibility=hidden
In file included from src/qpdf/qpdf.cpp:32:
src/qpdf/mmap_inputsource.h: In member function ‘virtual size_t MmapInputSource::read(char*, size_t)’:
src/qpdf/mmap_inputsource.h:142:31: error: ‘QIntC’ has not been declared
  142 |         size_t len = std::min(QIntC::to_size(end_pos - this->offset), length);
      |                               ^~~~~
src/qpdf/mmap_inputsource.h:154:25: error: ‘QIntC’ has not been declared
  154 |         this->offset += QIntC::to_offset(len);
      |                         ^~~~~
```

**Comment by jbarlow83** [comment]
Yes, that was unintended breakage. Thanks for the report. Fixed in 1.17.1.
